### ISSUE TITLE
[Bug] Engerprise Policy generation borked...

### ISSUE THREAD

**Issue by Hammerfest** [allo-/firefox-profilemaker#220] opened 2020-12-18 20:28 UTC
Went through profile maker, chose none of the addons, declared not to have menu on all the time, etc etc.

Applied enterprise_policy folder to install directory.
On next start all of the addons where installed, menu on all the time, etc etc, didnt bother to check everything, didnt need to.

Went through tool again and did fresh profile, same thing occurred.

**Comment by allo-** [comment] 2020-12-18 20:41
I can reproduce the bug.

**Comment by allo-** [comment] 2020-12-18 20:50
With no addon I cannot reproduce, but httpseverywhere only leads to httpseverywhere + canvasblocker.

**Comment by allo-** [comment] 2020-12-18 20:53
"Disable System addon update" policy adds all addons.

I think it is some problem in the merging of the form data.

Somewhere here it should only add the policy when the option is checked. This works for updating the addons list and does not work for updating the enterprise policy:

https://github.com/allo-/firefox-profilemaker/blob/79ddef3918bb56b25d49d69973de9a0564988f53/forms.py#L56

**Comment by Hammerfest** [comment] 2020-12-18 20:55
> 
> 
> "Disable System addon update" policy adds all addons.
> 
> I think it is some problem in the merging of the form data.
> 
> Somewhere here it should only add the policy when the option is checked. This works for updating the addons list and does not work for updating the enterprise policy:
> 
> https://github.com/allo-/firefox-profilemaker/blob/79ddef3918bb56b25d49d69973de9a0564988f53/forms.py#L56

I did not use that policy, it was left off (its default state)

**Comment by allo-** [comment] 2020-12-18 21:00
> I did not use that policy

I just commented on my debugging.

The problem affects more enterprise policies and is probably caused by merging the policies of different forms. When you did not answer the questions on the tab at all, you don't get the addons. If I answer with only httpseverywhere, I get two addons. When changing an option with enterprise policy in another tab, I get many addons.

It must be something how the policies are merged together / how it is checked if the option is active. The linked code looks correctly, the enterprise_policy section is only touched when `cleaned_data[option["name"]]` is truthy, just like the addons list. Still they show different behavior.

**Comment by allo-** [comment] 2020-12-18 21:01
> httpseverywhere only leads to httpseverywhere + canvasblocker.

Looked like there could be an mistake by two settings files using the same option name, but it is not. And they are selected correctly for the addons list, but not when generating the enterprise policy.

**Comment by Hammerfest** [comment] 2020-12-18 21:02
10-4, first dev I have seen to debug in a ticket, i like it :D
TYVM for all your work

**Comment by allo-** [comment] 2020-12-18 21:03
Noting down right/wrong behavior is helpful when debugging later. And maybe someone else has an idea. I don't see it now, but it should be fixed soon as it is a rather big bug, which only didn't cause more harm because only few people are using the enterprise policy export.

**Comment by allo-** [comment] 2020-12-20 13:13
When saving the form with different combinations it sometimes gets the wrong result and sometimes not.

The linked code path should always reset the policy before merging the active options and I even get extensions in the list, which were never enabled in the session. If the parsing would be wrong, they would be in the addons list as well, but they are not.

Please tell me, if you noticed a pattern. It looks to me like the extensions in the list before the last enabled extension are enabled as well, but not always.

As test cases: https-everywhere (only) enables cookie autodelete. uMatrix only seems not to enable everything before.

**Comment by allo-** [comment] 2022-09-21 17:44
@Hammerfest I believe this may be fixed by the latest commit. Can you test again?

**Comment by Hammerfest** [comment] 2022-09-21 17:48
> @Hammerfest I believe this may be fixed by the latest commit. Can you test again?

Will give it a go when I can this weekend

**Closed** 2023-06-30 09:41 UTC
Labels: bug, help wanted, Infrastructure
