### ISSUE TITLE
Firefox 60 does not remember last window size and position.

### ISSUE THREAD

**Issue by StarPicard** [allo-/firefox-profilemaker#117] opened 2018-05-12 18:37 UTC
Hey, in the default profile there must be an option which causes problems with the size and last position of Firefox. I'm currently diving into it, but I would be very happy if someone has any suggestion.

Specific behavior: After generating a new profile everything just works fine. After implementing the options from prefs.js the last window size and position is not remembered after restart.

**Comment by allo-** [comment] 2018-05-12 18:41
Have a look if resistfingerprinting affects this. Choosing a default window size is a part of the tor browser and resistfingerprinting backports these features.

**Comment by StarPicard** [comment] 2018-05-14 07:37
Yep, that's the switch responsible for the behavior. Maybe it should be disabled by default because it might disturb some users. We could try to figure out the option it enables and then include them manual. 
As i understand it it is not possible to keep this option and disable the window behavior.

**Comment by allo-** [comment] 2018-05-14 17:12
This is part of a much bigger issue, see https://github.com/allo-/firefox-profilemaker/issues/56#issuecomment-333397712 for a discussion about resistFingerprinting.

Resist Fingerprinting is able to replace a lot of the features here, but also overrides settings you want to change. For example you cannot override the useragent string when resistFingerprinting is active as it uses a default UA string.

**Comment by StarPicard** [comment] 2018-05-14 18:04
Mhm okay. seems to be a great deal, but for me it sounds very intransparent. I will disable it in my installs.

**Comment by allo-** [comment] 2018-05-14 18:14
I am considering disabling it by default and adding quite a bit of explanation.

**Comment by Atavic** [comment] 2018-12-02 12:52
The browser's window size is used for fingerprinting. Moreover, *Window innerWidth and innerHeight Property* is used to define exactly which browser is used. This kind of  fingerprinting is affecting Tor Browser (when not set to High Security Settings).

**Comment by allo-** [comment] 2018-12-02 13:00
Window size fingerprinting *is* a real issue even without javascript, see this CSS demo: https://www.parckwart.de/css_tracking

**Comment by allo-** [comment] 2018-12-02 14:06
I think the perfect tor setup is out of scope here and most people want sites to fit to their screen size.
The question here is if the profile should stick to resistFingerprinting by default or reproduce all (useful) parts of it as single settings.
See the comment linked above, resistFingerprinting is a nice one-click solution, but disables a lot of finetuning options.

**Comment by Atavic** [comment] 2018-12-02 14:10
To remember window position resistFingerprinting should be deactivated.

**Comment by allo-** [comment] 2021-05-06 14:13
I close here. This is resistFingerprinting working as intended. One may want to disable resistsFingerprinting and use other settings, see #56.

**Closed by allo-** 2021-05-06 14:13 UTC
Labels: breaks firefox features, help wanted, resistFingerprinting
